// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/checkout/data/repositories/checkout_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_app/config/base_response/base_response.dart' as _i5;
import 'package:flower_app/features/checkout/api/api_client/checkout_api_client.dart'
    as _i2;
import 'package:flower_app/features/checkout/data/data_sources/checkout_remote_data_source_contract.dart'
    as _i3;
import 'package:flower_app/features/checkout/data/models/request/checkout_request.dart'
    as _i7;
import 'package:flower_app/features/checkout/data/models/response/cash/cash_checkout_response_dto.dart'
    as _i6;
import 'package:flower_app/features/checkout/data/models/response/credit_card/credit_card_checkout_response_dto.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCheckoutApiClient_0 extends _i1.SmartFake
    implements _i2.CheckoutApiClient {
  _FakeCheckoutApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CheckoutRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckoutRemoteDataSourceContract extends _i1.Mock
    implements _i3.CheckoutRemoteDataSourceContract {
  MockCheckoutRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CheckoutApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeCheckoutApiClient_0(
              this,
              Invocation.getter(#apiClient),
            ),
          )
          as _i2.CheckoutApiClient);

  @override
  _i4.Future<_i5.BaseResponse<_i6.CashCheckoutResponseDto>> checkoutCashOrder(
    _i7.CheckoutRequest? checkoutRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkoutCashOrder, [checkoutRequest]),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i6.CashCheckoutResponseDto>>.value(
                  _i8.dummyValue<_i5.BaseResponse<_i6.CashCheckoutResponseDto>>(
                    this,
                    Invocation.method(#checkoutCashOrder, [checkoutRequest]),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.CashCheckoutResponseDto>>);

  @override
  _i4.Future<_i5.BaseResponse<_i9.CreditCardCheckoutResponseDto>>
  checkoutCreditCardOrder(String? url, _i7.CheckoutRequest? checkoutRequest) =>
      (super.noSuchMethod(
            Invocation.method(#checkoutCreditCardOrder, [url, checkoutRequest]),
            returnValue:
                _i4.Future<
                  _i5.BaseResponse<_i9.CreditCardCheckoutResponseDto>
                >.value(
                  _i8.dummyValue<
                    _i5.BaseResponse<_i9.CreditCardCheckoutResponseDto>
                  >(
                    this,
                    Invocation.method(#checkoutCreditCardOrder, [
                      url,
                      checkoutRequest,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i9.CreditCardCheckoutResponseDto>>);
}
