// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/auth/forget_password/api/data_sources/forget_password_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flower_app/features/auth/forget_password/api/api_client/forget_password_api_client.dart'
    as _i5;
import 'package:flower_app/features/auth/forget_password/data/models/requests/enter_reset_email_request.dart'
    as _i7;
import 'package:flower_app/features/auth/forget_password/data/models/requests/reset_password_request.dart'
    as _i9;
import 'package:flower_app/features/auth/forget_password/data/models/requests/verify_reset_code_request.dart'
    as _i8;
import 'package:flower_app/features/auth/forget_password/data/models/responses/enter_reset_email_dto.dart'
    as _i2;
import 'package:flower_app/features/auth/forget_password/data/models/responses/reset_password_dto.dart'
    as _i4;
import 'package:flower_app/features/auth/forget_password/data/models/responses/verify_reset_code_dto.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEnterResetEmailDTO_0 extends _i1.SmartFake
    implements _i2.EnterResetEmailDTO {
  _FakeEnterResetEmailDTO_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeDTO_1 extends _i1.SmartFake
    implements _i3.VerifyResetCodeDTO {
  _FakeVerifyResetCodeDTO_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordDTO_2 extends _i1.SmartFake
    implements _i4.ResetPasswordDTO {
  _FakeResetPasswordDTO_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ForgetPasswordApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordApiClient extends _i1.Mock
    implements _i5.ForgetPasswordApiClient {
  MockForgetPasswordApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.EnterResetEmailDTO> enterResetEmail(
    _i7.EnterResetEmailRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#enterResetEmail, [request]),
            returnValue: _i6.Future<_i2.EnterResetEmailDTO>.value(
              _FakeEnterResetEmailDTO_0(
                this,
                Invocation.method(#enterResetEmail, [request]),
              ),
            ),
          )
          as _i6.Future<_i2.EnterResetEmailDTO>);

  @override
  _i6.Future<_i3.VerifyResetCodeDTO> verifyResetCode(
    _i8.VerifyResetCodeRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue: _i6.Future<_i3.VerifyResetCodeDTO>.value(
              _FakeVerifyResetCodeDTO_1(
                this,
                Invocation.method(#verifyResetCode, [request]),
              ),
            ),
          )
          as _i6.Future<_i3.VerifyResetCodeDTO>);

  @override
  _i6.Future<_i4.ResetPasswordDTO> resetPassword(
    _i9.ResetPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i6.Future<_i4.ResetPasswordDTO>.value(
              _FakeResetPasswordDTO_2(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i6.Future<_i4.ResetPasswordDTO>);
}
