// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/orders/data/repo/orders_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flower_app/features/orders/data/data_sources/orders_remote_data_source_contract.dart'
    as _i4;
import 'package:flower_app/features/orders/data/models/meta_data.dart' as _i6;
import 'package:flower_app/features/orders/data/models/orders.dart' as _i7;
import 'package:flower_app/features/orders/data/models/orders_response_dto.dart'
    as _i2;
import 'package:flower_app/features/orders/domain/models/orders_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOrdersResponseDto_0 extends _i1.SmartFake
    implements _i2.OrdersResponseDto {
  _FakeOrdersResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrdersModel_1 extends _i1.SmartFake implements _i3.OrdersModel {
  _FakeOrdersModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrdersRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrdersRemoteDataSource extends _i1.Mock
    implements _i4.OrdersRemoteDataSource {
  MockOrdersRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.OrdersResponseDto> getUserOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getUserOrders, []),
            returnValue: _i5.Future<_i2.OrdersResponseDto>.value(
              _FakeOrdersResponseDto_0(
                this,
                Invocation.method(#getUserOrders, []),
              ),
            ),
          )
          as _i5.Future<_i2.OrdersResponseDto>);
}

/// A class which mocks [OrdersResponseDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrdersResponseDto extends _i1.Mock implements _i2.OrdersResponseDto {
  MockOrdersResponseDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set message(String? value) => super.noSuchMethod(
    Invocation.setter(#message, value),
    returnValueForMissingStub: null,
  );

  @override
  set metadata(_i6.Metadata? value) => super.noSuchMethod(
    Invocation.setter(#metadata, value),
    returnValueForMissingStub: null,
  );

  @override
  set orders(List<_i7.Orders>? value) => super.noSuchMethod(
    Invocation.setter(#orders, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [Orders].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrders extends _i1.Mock implements _i7.Orders {
  MockOrders() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set id(String? value) => super.noSuchMethod(
    Invocation.setter(#id, value),
    returnValueForMissingStub: null,
  );

  @override
  set user(String? value) => super.noSuchMethod(
    Invocation.setter(#user, value),
    returnValueForMissingStub: null,
  );

  @override
  set orderItems(List<dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#orderItems, value),
    returnValueForMissingStub: null,
  );

  @override
  set totalPrice(int? value) => super.noSuchMethod(
    Invocation.setter(#totalPrice, value),
    returnValueForMissingStub: null,
  );

  @override
  set paymentType(String? value) => super.noSuchMethod(
    Invocation.setter(#paymentType, value),
    returnValueForMissingStub: null,
  );

  @override
  set isPaid(bool? value) => super.noSuchMethod(
    Invocation.setter(#isPaid, value),
    returnValueForMissingStub: null,
  );

  @override
  set isDelivered(bool? value) => super.noSuchMethod(
    Invocation.setter(#isDelivered, value),
    returnValueForMissingStub: null,
  );

  @override
  set state(String? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  set createdAt(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#createdAt, value),
    returnValueForMissingStub: null,
  );

  @override
  set updatedAt(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#updatedAt, value),
    returnValueForMissingStub: null,
  );

  @override
  set orderNumber(String? value) => super.noSuchMethod(
    Invocation.setter(#orderNumber, value),
    returnValueForMissingStub: null,
  );

  @override
  set v(int? value) => super.noSuchMethod(
    Invocation.setter(#v, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.OrdersModel toDomain() =>
      (super.noSuchMethod(
            Invocation.method(#toDomain, []),
            returnValue: _FakeOrdersModel_1(
              this,
              Invocation.method(#toDomain, []),
            ),
          )
          as _i3.OrdersModel);
}
