// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/checkout/api/data_sources/checkout_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flower_app/features/checkout/api/api_client/checkout_api_client.dart'
    as _i4;
import 'package:flower_app/features/checkout/data/models/request/checkout_request.dart'
    as _i6;
import 'package:flower_app/features/checkout/data/models/response/cash/cash_checkout_response_dto.dart'
    as _i2;
import 'package:flower_app/features/checkout/data/models/response/credit_card/credit_card_checkout_response_dto.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCashCheckoutResponseDto_0 extends _i1.SmartFake
    implements _i2.CashCheckoutResponseDto {
  _FakeCashCheckoutResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreditCardCheckoutResponseDto_1 extends _i1.SmartFake
    implements _i3.CreditCardCheckoutResponseDto {
  _FakeCreditCardCheckoutResponseDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [CheckoutApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckoutApiClient extends _i1.Mock implements _i4.CheckoutApiClient {
  MockCheckoutApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.CashCheckoutResponseDto> checkoutCashOrder(
    _i6.CheckoutRequest? checkoutRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkoutCashOrder, [checkoutRequest]),
            returnValue: _i5.Future<_i2.CashCheckoutResponseDto>.value(
              _FakeCashCheckoutResponseDto_0(
                this,
                Invocation.method(#checkoutCashOrder, [checkoutRequest]),
              ),
            ),
          )
          as _i5.Future<_i2.CashCheckoutResponseDto>);

  @override
  _i5.Future<_i3.CreditCardCheckoutResponseDto> checkoutCreditCardOrder(
    String? url,
    _i6.CheckoutRequest? checkoutRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkoutCreditCardOrder, [url, checkoutRequest]),
            returnValue: _i5.Future<_i3.CreditCardCheckoutResponseDto>.value(
              _FakeCreditCardCheckoutResponseDto_1(
                this,
                Invocation.method(#checkoutCreditCardOrder, [
                  url,
                  checkoutRequest,
                ]),
              ),
            ),
          )
          as _i5.Future<_i3.CreditCardCheckoutResponseDto>);
}
