// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/forget_password/presentation/view_model/cubit/forget_password_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_app/config/base_response/base_response.dart' as _i5;
import 'package:flower_app/features/forget_password/data/models/requests/enter_reset_email_request.dart'
    as _i7;
import 'package:flower_app/features/forget_password/data/models/requests/reset_password_request.dart'
    as _i14;
import 'package:flower_app/features/forget_password/data/models/requests/verify_reset_code_request.dart'
    as _i11;
import 'package:flower_app/features/forget_password/domain/entities/enter_reset_email_entity.dart'
    as _i6;
import 'package:flower_app/features/forget_password/domain/entities/reset_password_entity.dart'
    as _i13;
import 'package:flower_app/features/forget_password/domain/entities/verify_reset_code_entity.dart'
    as _i10;
import 'package:flower_app/features/forget_password/domain/repositories/forget_password_repo_contract.dart'
    as _i2;
import 'package:flower_app/features/forget_password/domain/use_cases/enter_reset_email_use_case.dart'
    as _i3;
import 'package:flower_app/features/forget_password/domain/use_cases/reset_password_use_case.dart'
    as _i12;
import 'package:flower_app/features/forget_password/domain/use_cases/verify_reset_code_use_case.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeForgetPasswordRepoContract_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordRepoContract {
  _FakeForgetPasswordRepoContract_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EnterResetEmailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnterResetEmailUseCase extends _i1.Mock
    implements _i3.EnterResetEmailUseCase {
  MockEnterResetEmailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ForgetPasswordRepoContract get forgetPasswordRepoContract =>
      (super.noSuchMethod(
            Invocation.getter(#forgetPasswordRepoContract),
            returnValue: _FakeForgetPasswordRepoContract_0(
              this,
              Invocation.getter(#forgetPasswordRepoContract),
            ),
          )
          as _i2.ForgetPasswordRepoContract);

  @override
  _i4.Future<_i5.BaseResponse<_i6.EnterResetEmailEntity>> call(
    _i7.EnterResetEmailRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [request]),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i6.EnterResetEmailEntity>>.value(
                  _i8.dummyValue<_i5.BaseResponse<_i6.EnterResetEmailEntity>>(
                    this,
                    Invocation.method(#call, [request]),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.EnterResetEmailEntity>>);
}

/// A class which mocks [VerifyResetCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyResetCodeUseCase extends _i1.Mock
    implements _i9.VerifyResetCodeUseCase {
  MockVerifyResetCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ForgetPasswordRepoContract get forgetPasswordRepoContract =>
      (super.noSuchMethod(
            Invocation.getter(#forgetPasswordRepoContract),
            returnValue: _FakeForgetPasswordRepoContract_0(
              this,
              Invocation.getter(#forgetPasswordRepoContract),
            ),
          )
          as _i2.ForgetPasswordRepoContract);

  @override
  _i4.Future<_i5.BaseResponse<_i10.VerifyResetCodeEntity>> call(
    _i11.VerifyResetCodeRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [request]),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i10.VerifyResetCodeEntity>>.value(
                  _i8.dummyValue<_i5.BaseResponse<_i10.VerifyResetCodeEntity>>(
                    this,
                    Invocation.method(#call, [request]),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i10.VerifyResetCodeEntity>>);
}

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i12.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ForgetPasswordRepoContract get forgetPasswordRepoContract =>
      (super.noSuchMethod(
            Invocation.getter(#forgetPasswordRepoContract),
            returnValue: _FakeForgetPasswordRepoContract_0(
              this,
              Invocation.getter(#forgetPasswordRepoContract),
            ),
          )
          as _i2.ForgetPasswordRepoContract);

  @override
  _i4.Future<_i5.BaseResponse<_i13.ResetPasswordEntity>> call(
    _i14.ResetPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [request]),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i13.ResetPasswordEntity>>.value(
                  _i8.dummyValue<_i5.BaseResponse<_i13.ResetPasswordEntity>>(
                    this,
                    Invocation.method(#call, [request]),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i13.ResetPasswordEntity>>);
}
