// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/app_sections/cart/presentation/view_model/cubit/cart_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_app/config/base_response/base_response.dart' as _i5;
import 'package:flower_app/features/app_sections/cart/data/models/request/add_to_cart_request.dart'
    as _i9;
import 'package:flower_app/features/app_sections/cart/data/models/request/update_cart_item_quantity_request.dart'
    as _i12;
import 'package:flower_app/features/app_sections/cart/domain/entities/cart_response_entity.dart'
    as _i6;
import 'package:flower_app/features/app_sections/cart/domain/repositories/cart_repo_contract.dart'
    as _i2;
import 'package:flower_app/features/app_sections/cart/domain/use_cases/add_item_to_cart_use_case.dart'
    as _i8;
import 'package:flower_app/features/app_sections/cart/domain/use_cases/get_items_cart_use_case.dart'
    as _i3;
import 'package:flower_app/features/app_sections/cart/domain/use_cases/remove_item_from_cart_use_case.dart'
    as _i10;
import 'package:flower_app/features/app_sections/cart/domain/use_cases/update_cart_item_quantity_use_case.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCartRepoContract_0 extends _i1.SmartFake
    implements _i2.CartRepoContract {
  _FakeCartRepoContract_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetItemsCartUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetItemsCartUseCase extends _i1.Mock
    implements _i3.GetItemsCartUseCase {
  MockGetItemsCartUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CartRepoContract get cartRepoContract =>
      (super.noSuchMethod(
            Invocation.getter(#cartRepoContract),
            returnValue: _FakeCartRepoContract_0(
              this,
              Invocation.getter(#cartRepoContract),
            ),
          )
          as _i2.CartRepoContract);

  @override
  _i4.Future<_i5.BaseResponse<_i6.CartResponseEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i6.CartResponseEntity>>.value(
                  _i7.dummyValue<_i5.BaseResponse<_i6.CartResponseEntity>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.CartResponseEntity>>);
}

/// A class which mocks [AddItemToCartUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddItemToCartUseCase extends _i1.Mock
    implements _i8.AddItemToCartUseCase {
  MockAddItemToCartUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CartRepoContract get cartRepoContract =>
      (super.noSuchMethod(
            Invocation.getter(#cartRepoContract),
            returnValue: _FakeCartRepoContract_0(
              this,
              Invocation.getter(#cartRepoContract),
            ),
          )
          as _i2.CartRepoContract);

  @override
  _i4.Future<_i5.BaseResponse<_i6.CartResponseEntity>> call(
    _i9.AddToCartRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [request]),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i6.CartResponseEntity>>.value(
                  _i7.dummyValue<_i5.BaseResponse<_i6.CartResponseEntity>>(
                    this,
                    Invocation.method(#call, [request]),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.CartResponseEntity>>);
}

/// A class which mocks [RemoveItemFromCartUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveItemFromCartUseCase extends _i1.Mock
    implements _i10.RemoveItemFromCartUseCase {
  MockRemoveItemFromCartUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CartRepoContract get cartRepoContract =>
      (super.noSuchMethod(
            Invocation.getter(#cartRepoContract),
            returnValue: _FakeCartRepoContract_0(
              this,
              Invocation.getter(#cartRepoContract),
            ),
          )
          as _i2.CartRepoContract);

  @override
  _i4.Future<_i5.BaseResponse<_i6.CartResponseEntity>> call(
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [productId]),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i6.CartResponseEntity>>.value(
                  _i7.dummyValue<_i5.BaseResponse<_i6.CartResponseEntity>>(
                    this,
                    Invocation.method(#call, [productId]),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.CartResponseEntity>>);
}

/// A class which mocks [UpdateCartItemQuantityUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateCartItemQuantityUseCase extends _i1.Mock
    implements _i11.UpdateCartItemQuantityUseCase {
  MockUpdateCartItemQuantityUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.BaseResponse<_i6.CartResponseEntity>> call(
    String? productId,
    _i12.UpdateCartQuantityRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [productId, request]),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i6.CartResponseEntity>>.value(
                  _i7.dummyValue<_i5.BaseResponse<_i6.CartResponseEntity>>(
                    this,
                    Invocation.method(#call, [productId, request]),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.CartResponseEntity>>);
}
