// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/orders/api/data_sources/orders_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_app/features/orders/api/api_client/orders_api_client.dart'
    as _i3;
import 'package:flower_app/features/orders/data/models/orders_response_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOrdersResponseDto_0 extends _i1.SmartFake
    implements _i2.OrdersResponseDto {
  _FakeOrdersResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrdersApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrdersApiClient extends _i1.Mock implements _i3.OrdersApiClient {
  MockOrdersApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.OrdersResponseDto> getUserOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getUserOrders, []),
            returnValue: _i4.Future<_i2.OrdersResponseDto>.value(
              _FakeOrdersResponseDto_0(
                this,
                Invocation.method(#getUserOrders, []),
              ),
            ),
          )
          as _i4.Future<_i2.OrdersResponseDto>);
}
